name: issue
author: rishabhgupta
description: Opens a github issue
inputs:
  token:
    description: "Github Token"
    required: true
  title:
    description: "Issue Title"
    required: true
  body:
    description: "Issue Body"
    required: false
  assignees:
    description: "Issue Assignee"
    required: false
outputs:
  issue: # id of output
    description: "The issue object as a json string"
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: "alert-triangle"
  color: "red"